# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /example
  # Name will be used as the value for the `app.kubernetes.io/component`
  # selector label and updated automatically by `kpt fn render`.
  # So no need to set those manually.
  name: server
  labels:
    app.kubernetes.io/component: server
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|example'
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: default
          image: "obs-portal-frontend"
          env:
            - name: INTERNAL_OBSERVATION_PORTAL_API_URL
              valueFrom:
                configMapKeyRef:
                  key: INTERNAL_OBSERVATION_PORTAL_API_URL
                  name: env
                  optional: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /help
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /help
              port: http
          volumeMounts:
            - name: app-configuration
              mountPath: /app/config
              readOnly: true
            - name: nginx-var-cache-nginx
              mountPath: /var/cache/nginx
              readOnly: false
            - name: nginx-var-run
              mountPath: /var/run
              readOnly: false
            - name: init
              mountPath: /init
              readOnly: false
      volumes:
        - name: app-configuration
          configMap:
            name: app-config
            optional: false
        - name: nginx-var-cache-nginx
          emptyDir:
            sizeLimit: 128Mi
        - name: init
          emptyDir:
            sizeLimit: 16Mi
        - name: nginx-var-run
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
