# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: obs-portal-frontend
