apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-server/
  - ./svc-server/

labels:
  - pairs:
      app.kubernetes.io/name: obs-portal-frontend
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - name: app-config
    files:
      - urls.json
